# -*- coding: utf-8 -*-
"""NOAA_EDA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ck3iB3C0gqZWSQb3VA4glYm_wgM7Gx-T
"""

# vjIpaNKxJbEDODuiQNRXxDujdLHmWbgt
#!pip install cdo-api-py
api_token = "aIILvsLDvkAbPPvZagdxBFTVeemdZEVq"

from cdo_api_py import Client
import pandas as pd
from datetime import datetime
from pprint import pprint    # be sure not to share your token publicly
my_client = Client(api_token, default_units=None, default_limit=1000)

extent = {
    "north": 37.18,
    "south": 25.51,
    "east": -92.27,
    "west": -111.97,
}

startdate = datetime(2010, 12, 1)
enddate = datetime(2019, 12, 31)

datasetid='GHCND'
datatypeid=['TMIN', 'TMAX', 'PRCP', 'WSF5', 'WSF2']

pprint(my_client.list_datasets())

stations = my_client.find_stations(
    datasetid=datasetid,
    extent=extent,
    startdate=startdate,
    enddate=enddate,
    datatypeid=datatypeid,
    return_dataframe=True)
pprint(stations)

txstations = stations[stations['name'].str.contains("TX US")]
txstations.shape

txstations

big_df = pd.DataFrame()
try:
	for rowid, station in txstations.iterrows():  # remember this is a pandas dataframe!
		station_data = my_client.get_data_by_station(
			datasetid=datasetid,
			stationid=station['id'],
			startdate=startdate,
			enddate=enddate,
			return_dataframe=True,
			include_station_meta=True   # flatten station metadata with ghcnd readings
		)
		pprint(station_data)
		big_df = pd.concat([big_df, station_data])
except Exception as e:
	print(str(e))
	pass

print(big_df)
big_df = big_df.sort_values(by='date').reset_index()

big_df.head()
big_df.to_csv('raw_ghcnd.csv',index=False)
doecol=big_df.describe().columns.tolist()
print('\n'.join(['{0} : {1}'.format(col,big_df[col].unique().tolist()) for col in doecol if not pd.isna(big_df[col].unique().tolist()).all()]))
doecol=[col for col in doecol if not pd.isna(big_df[col].unique().tolist()).all()]

# from google.colab import drive
# drive.mount('/content/gdrive')

# big_df[big_df['WT11'] == 1.0].describe()

# !ls /content/gdrive/My\ Drive
# big_df.to_csv(r'/content/gdrive/My Drive/Houston_GHCND.csv',index=False)